"""update fields load

Revision ID: 1dcbb88daa94
Revises: 01935b91e54d
Create Date: 2022-11-26 10:48:49.868681

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1dcbb88daa94'
down_revision = '01935b91e54d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
