"""fix loads

Revision ID: 1dd7134dd8c6
Revises: 625cbb1861cf
Create Date: 2022-12-04 11:32:40.737006

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dd7134dd8c6'
down_revision = '625cbb1861cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('load', 'discipline_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('load', 'discipline_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
