"""optional disc_id

Revision ID: 27e269655881
Revises: f9a4d07a9095
Create Date: 2022-11-26 17:14:12.205377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '27e269655881'
down_revision = 'f9a4d07a9095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
