"""added new models

Revision ID: 305da0734ffa
Revises: c1dfa98f379b
Create Date: 2022-11-18 08:35:42.290702

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '305da0734ffa'
down_revision = 'c1dfa98f379b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'hiring_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'hiring_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
