"""update load

Revision ID: 31e5cd08cf3d
Revises: 753c92ea39a1
Create Date: 2022-11-26 18:02:05.082346

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '31e5cd08cf3d'
down_revision = '753c92ea39a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
