"""teacher auth 2

Revision ID: 39e82acd7559
Revises: 57c6c8a810d7
Create Date: 2022-12-04 15:59:13.803742

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '39e82acd7559'
down_revision = '57c6c8a810d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
