"""updating department

Revision ID: 55b90e727b00
Revises: ea71c3b3094a
Create Date: 2022-11-18 15:57:33.643610

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '55b90e727b00'
down_revision = 'ea71c3b3094a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
