"""teacher auth

Revision ID: 57c6c8a810d7
Revises: d7da0fe1b303
Create Date: 2022-12-04 15:47:28.433454

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '57c6c8a810d7'
down_revision = 'd7da0fe1b303'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
