"""added relationships for students

Revision ID: 625cbb1861cf
Revises: 710970c0cbb3
Create Date: 2022-12-02 16:54:03.258293

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '625cbb1861cf'
down_revision = '710970c0cbb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
