"""added students, groups, speciality models

Revision ID: 6d8a8f5c6834
Revises: 4a9c61f347de
Create Date: 2022-11-18 09:17:50.469170

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d8a8f5c6834'
down_revision = '4a9c61f347de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgroup',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialily_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['specialily_id'], ['speciality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('perfomance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_group_id'], ['sgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('department', sa.Column('foundation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('teacher', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('department', 'foundation_date')
    op.drop_table('student')
    op.drop_table('sgroup')
    # ### end Alembic commands ###
