"""fix loads 8

Revision ID: 6dd1a9ed0597
Revises: 70fce1f865b4
Create Date: 2022-12-04 12:03:34.500623

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6dd1a9ed0597'
down_revision = '70fce1f865b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
