"""fix loads 7

Revision ID: 70fce1f865b4
Revises: 7b9c539d695f
Create Date: 2022-12-04 12:02:23.750004

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '70fce1f865b4'
down_revision = '7b9c539d695f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
