"""fix foreign key links table

Revision ID: 710970c0cbb3
Revises: 31e5cd08cf3d
Create Date: 2022-11-26 18:04:11.346097

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '710970c0cbb3'
down_revision = '31e5cd08cf3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupstudyloadlink', sa.Column('study_load_id', sa.Integer(), nullable=False))
    op.drop_constraint('groupstudyloadlink_ibfk_2', 'groupstudyloadlink', type_='foreignkey')
    op.create_foreign_key(None, 'groupstudyloadlink', 'load', ['study_load_id'], ['id'])
    op.drop_column('groupstudyloadlink', 'study_laod_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupstudyloadlink', sa.Column('study_laod_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groupstudyloadlink', type_='foreignkey')
    op.create_foreign_key('groupstudyloadlink_ibfk_2', 'groupstudyloadlink', 'load', ['study_laod_id'], ['id'])
    op.drop_column('groupstudyloadlink', 'study_load_id')
    # ### end Alembic commands ###
