"""update load

Revision ID: 753c92ea39a1
Revises: 8ea17d56812b
Create Date: 2022-11-26 17:53:48.423915

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '753c92ea39a1'
down_revision = '8ea17d56812b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
