"""fix loads 6

Revision ID: 7b9c539d695f
Revises: b1f553e0df35
Create Date: 2022-12-04 11:55:41.465433

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7b9c539d695f'
down_revision = 'b1f553e0df35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
