"""fix load to Load

Revision ID: abfdaf3e98eb
Revises: b4f06708f9e9
Create Date: 2022-11-26 16:05:00.710120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'abfdaf3e98eb'
down_revision = 'b4f06708f9e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
