"""fix loads 5

Revision ID: b1f553e0df35
Revises: b2b52b3eee9a
Create Date: 2022-12-04 11:53:10.065440

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b1f553e0df35'
down_revision = 'b2b52b3eee9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
