"""fix loads 4

Revision ID: b2b52b3eee9a
Revises: d61b61a5abf1
Create Date: 2022-12-04 11:50:25.580529

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b2b52b3eee9a'
down_revision = 'd61b61a5abf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
