"""try to fix models 2

Revision ID: b4f06708f9e9
Revises: d9a2279d4cd2
Create Date: 2022-11-26 11:06:09.355978

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b4f06708f9e9'
down_revision = 'd9a2279d4cd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
