"""updated teacher model, added department, admin models

Revision ID: c1dfa98f379b
Revises: d79821978e23
Create Date: 2022-11-17 15:43:41.637289

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1dfa98f379b'
down_revision = 'd79821978e23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('hiring_date', sa.Date(), nullable=True))
    op.add_column('teacher', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('teacher', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('teacher', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'department', ['department_id'], ['id'])
    op.drop_column('teacher', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'department_id')
    op.drop_column('teacher', 'password')
    op.drop_column('teacher', 'email')
    op.drop_column('teacher', 'hiring_date')
    op.drop_column('teacher', 'middle_name')
    op.drop_column('teacher', 'first_name')
    op.drop_column('teacher', 'last_name')
    op.drop_table('department')
    op.drop_table('admin')
    # ### end Alembic commands ###
