"""fix loads 3

Revision ID: d61b61a5abf1
Revises: e70810112624
Create Date: 2022-12-04 11:44:34.827454

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd61b61a5abf1'
down_revision = 'e70810112624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
