"""fix loads 8

Revision ID: d7da0fe1b303
Revises: 6dd1a9ed0597
Create Date: 2022-12-04 12:04:08.441841

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd7da0fe1b303'
down_revision = '6dd1a9ed0597'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
