"""try to fix models

Revision ID: d9a2279d4cd2
Revises: fc45af114bfa
Create Date: 2022-11-26 11:04:44.466573

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd9a2279d4cd2'
down_revision = 'fc45af114bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
