"""renamed passwords fields

Revision ID: e390f8c2e796
Revises: 5d3cf559e5f8
Create Date: 2022-11-18 09:40:36.279901

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e390f8c2e796'
down_revision = '5d3cf559e5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('admin', 'password')
    op.add_column('teacher', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('teacher', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('teacher', 'password_hash')
    op.add_column('admin', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('admin', 'password_hash')
    # ### end Alembic commands ###
