"""fix loads 2

Revision ID: e70810112624
Revises: 1dd7134dd8c6
Create Date: 2022-12-04 11:39:02.645933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e70810112624'
down_revision = '1dd7134dd8c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
