"""optional disc_id

Revision ID: f9a4d07a9095
Revises: abfdaf3e98eb
Create Date: 2022-11-26 17:09:28.491183

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9a4d07a9095'
down_revision = 'abfdaf3e98eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('load', 'discipline_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('load', 'discipline_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
