"""try to fix authorize

Revision ID: fc45af114bfa
Revises: 1dcbb88daa94
Create Date: 2022-11-26 10:54:38.792856

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fc45af114bfa'
down_revision = '1dcbb88daa94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
